### ISSUE TITLE
Checkmark missing on some items

### ISSUE THREAD

**Issue by Layemeraude** [AeonSake/acnh-catalogue-issues#34]
Hi!

Just a small thing, I've noticed the checkmark isn't available for the golden ladder set-up kit and the iron ladder set-up kit in the list of tools, same for all the pillars in the list of furniture.

**Comment by AeonSake** [comment]
By default, only items that show up in the Nook Shopping catalog or any other source that can checked (e.g., museum collections, DIYs, etc.) have a checkmark. The items you have mentioned don't show up in the Nook Shopping catalog (or any other source), that's why they don't have a checkmark. However, you can force that feature by enabling the `Make all entries checkable` option in the advanced settings menu.

**Comment by Layemeraude** [comment]
Okay thank you, I've found the option! Thanks!
