### ISSUE TITLE
Seasonal Events: the halloween preparation is missing some items such as the spooky carriage or spooky wand

### ISSUE THREAD

**Issue by MarchWarrant** [AeonSake/acnh-catalogue-issues#39]
Seasonal Events: the halloween preparation is missing some items featured such as the spooky carriage or the spooky wand
Edit: never mind, they are covered in the halloween tab so i guess you can't get these items vefore halloween aka during prep
so it's correct already, my bad

**Comment by AeonSake** [comment]
Yes, some items are exclusively obtained from Jack, therefore not part of the "Halloween (preparation)" event period. That's why there are two events related to halloween ("Halloween (preparation)" and "Halloween"), since the game also handles them separately.
I'll close this issue for now unless you find something else that is wrong.
